### ISSUE TITLE
Internet 

### ISSUE THREAD

**Issue by Adityapro9** [termux-desktop/termux-desktop-lxqt#24]
Browser getting error

**Comment by st0rmc4non** [comment]
Take a look at #22 , or use NetSurf (launch from terminal)

**Comment by Adityapro9** [comment]
What is netsurf command

**Comment by Adityapro9** [comment]
CANNOT LINK EXECUTABLE "otter-browser": library "libicuuc.so.70" not found

**Comment by Yisus7u7** [comment]
this issue is straight from the termux repositories, please open the issue there.
